spring.application.name=Springboot-API-REST

# Configuración de la base de datos MySQL (Soporta inyección externa)
# Reemplaza la línea vieja por esta:
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/proyectosemestral
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
