name: CI/CD Backend Ventas

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back-Ventas_SpringBoot/**'
      - '.github/workflows/backend-ventas.yml'

env:
  AWS_REGION: us-east-1
  CONTAINER_NAME: back-ventas-container


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Desplegar en EC2 Privada (Ventas) mediante Bastión
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_VENTAS_IP }} 
        username: ec2-user
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        
        proxy_host: ${{ secrets.EC2_FRONTEND_IP }}
        proxy_username: ec2-user
        proxy_key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 572392556337.dkr.ecr.us-east-1.amazonaws.com
          
          docker pull 572392556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-back-ventas:v1
          
          docker stop proyectosemestral-back-ventas || true
          docker rm proyectosemestral-back-ventas || true
          
          docker run -d -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.EC2_DATABASE_IP }}:3306/db_sistema \
            -e SPRING_DATASOURCE_USERNAME=user_sistema \
            -e SPRING_DATASOURCE_PASSWORD=userpassword \
            --name proyectosemestral-back-ventas \
            572392556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-back-ventas:v1
            
          # 6. Limpiar credenciales por seguridad
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN