name: Deploy Frontend desde ECR

on:
  push:
    branches: [ "main" ] # Se activará cuando hagas un push a main para iniciar el despliegue
    paths:
      - 'front_despacho/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Solo nos conectamos directamente a la EC2 por SSH
    - name: Desplegar en EC2 pública mediante SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_FRONTEND_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          # 2. Autenticar Docker con tu ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 572392556337.dkr.ecr.us-east-1.amazonaws.com
          
          # 3. Traer (PULL) la imagen desde ECR hacia la EC2
          docker pull 572392556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-frontend:latest
          
          # 4. Detener y limpiar el contenedor anterior si existe
          docker stop proyectosemestral-frontend || true
          docker rm proyectosemestral-frontend || true
          
          # 5. Correr el nuevo contenedor con la imagen fresca de ECR
          docker run -d -p 80:80 --name proyectosemestral-frontend 572392556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-frontend:latest
          
          # 6. Limpiar credenciales de la sesión de la terminal por seguridad
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN