name: Deploy Frontend desde ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'front_despacho/**'
      - '.github/workflows/frontend.yml'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Autenticar en AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Subir Imagen a ECR
      env:
        ECR_REGISTRY: 572392556337.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: proyectosemestral-frontend
        IMAGE_TAG: v2
      run: |
        # Build limpio sin URLs harcodeadas de AWS
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./front_despacho
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Desplegar en EC2 pública mediante SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_FRONTEND_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 572392556337.dkr.ecr.us-east-1.amazonaws.com
          docker pull 572392556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-frontend:v2
          docker stop proyectosemestral-frontend || true
          docker rm proyectosemestral-frontend || true
          
          # CORREGIDO: Pasamos las IPs privadas de tus Backends como variables de entorno al contenedor
          docker run -d -p 80:80 \
            -e EC2_VENTAS_IP=${{ secrets.EC2_VENTAS_IP }} \
            -e EC2_DESPACHOS_IP=${{ secrets.EC2_DESPACHOS_IP }} \
            --name proyectosemestral-frontend \
            572392556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-frontend:v2
            
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN