name: CI/CD Frontend

on:
  push:
    branches: [ "main" ]
    # OJO AQUÍ: Asegúrate de que tu carpeta local se llame 'front_despacho' o cambialo por 'proyectosemestral-frontend'
    paths:
      - 'front_despacho/**' 

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: proyectosemestral-frontend  # 1. CAMBIADO: Coincide con tu AWS ECR
  CONTAINER_NAME: front-despacho-container

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Autenticar en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Compilar y Subir Imagen a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        # 2. REVISIÓN: El comando docker build usa las variables definidas arriba
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./proyectosemestral-frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar en EC2 pública mediante SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_FRONTEND_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        # 3. CORREGIDO: Se reemplazaron variables del contexto local que fallarían por SSH
        script: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 572332556337.dkr.ecr.us-east-1.amazonaws.com
          docker pull 572332556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-frontend:latest
          docker stop front-despacho-container || true
          docker rm front-despacho-container || true
          docker run -d -p 80:80 --name front-despacho-container 572332556337.dkr.ecr.us-east-1.amazonaws.com/proyectosemestral-frontend:latest